name: stationeers_companion
services:
  laravel_app:
    build:
      context: /DATA/Projects/Laravel/stationeers_companion/docker/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: "1000"
    cpu_shares: 90
    command: []
    container_name: stationeers_companion
    deploy:
      resources:
        limits:
          memory: 4096M
    environment:
      - IGNITION_LOCAL_SITES_PATH=/DATA/Projects/Laravel/stationeers_companion
      - LARAVEL_SAIL=1
      - WWWUSER=werner
      - XDEBUG_CONFIG=client_host=host.docker.internal
      - XDEBUG_MODE=off
    hostname: stationeers_companion
    image: sail-8.3/app:latest
    labels:
      icon: https://raw.githubusercontent.com/WernerLuiz92/Stationeers_Companion_-_Game_Utility/main/resources/img/stationeers-companion_2.svg
    ports:
      - target: 80
        published: "10889"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Projects/Laravel/stationeers_companion
        target: /var/www/html
    devices: []
    cap_add: []
    network_mode: bridge
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://raw.githubusercontent.com/WernerLuiz92/Stationeers_Companion_-_Game_Utility/main/resources/img/stationeers-companion_2.svg
  index: /
  is_uncontrolled: false
  port_map: "10889"
  scheme: http
  store_app_id: stationeers_companion
  title:
    custom: Stationeers Companion
